const own_questions = [
    "What is the chemical formula for water?",
    "Explain the concept of gravity",
    "What are the properties of electromagnetic waves?",
    "How does stoichiometry apply to chemical reactions?",
    "What is the relationship between voltage and current in an electrical circuit?",
    "Explain the fundamental principle of the conservation of energy.",
    "What is the chemical structure of methane?",
    "How do chemical bonds form in molecules?",
    "What is the ideal gas law and its significance?",
    "What are the laws of motion according to Newton?",
    "Describe the electromagnetic spectrum and its regions.",
    "How does the periodic table organize chemical elements?",
    "What is the Bohr model of the atom?",
    "Explain the concept of valence electrons in atoms.",
    "How does acid-base chemistry work?",
    "What is the kinetic theory of gases?",
    "What is the role of catalysts in chemical reactions?",
    "How do light waves behave in different mediums?",
    "What is the difference between a physical and chemical change?",
    "How does heat transfer occur through conduction?",
    "What is the law of conservation of mass?",
    "Describe the structure of the Earth's atmosphere.",
    "Explain the concept of Avogadro's number.",
    "What is the role of enzymes in biological reactions?",
    "How do you balance chemical equations?",
    "What is the formula for sulfuric acid?",
    "Describe the process of photosynthesis in plants.",
    "What is the ideal gas constant?",
    "How is energy quantized in quantum mechanics?",
    "What is the difference between an element and a compound?",
    "What are the three states of matter?",
    "How do you calculate the molar mass of a compound?",
    "Explain the concept of oxidation and reduction in chemistry.",
    "What is the concept of momentum in physics?",
    "What is the law of reflection in optics?",
    "Describe the process of nuclear fusion in stars.",
    "What is the difference between velocity and acceleration?",
    "How does Boyle's law relate pressure and volume of gases?",
    "Explain the concept of isomers in organic chemistry.",
    "What is the relationship between wavelength and frequency of light waves?",
    "What is the conservation of angular momentum?",
    "How does electricity flow in a closed circuit?",
    "What is the concept of half-life in radioactive decay?",
    "Describe the process of chemical equilibrium.",
    "What are the properties of acids and bases?",
];

const actual_labels = [
    "chemistry",
    "physics",
    "physics",
    "chemistry",
    "physics",
    "physics",
    "chemistry",
    "chemistry",
    "chemistry",
    "physics",
    "physics",
    "chemistry",
    "physics",
    "chemistry",
    "chemistry",
    "physics",
    "chemistry",
    "physics",
    "chemistry",
    "physics",
    "chemistry",
    "physics",
    "physics",
    "chemistry",
    "chemistry",
    "physics",
    "chemistry",
    "physics",
    "chemistry",
    "chemistry",
    "physics",
    "chemistry",
    "physics",
    "physics",
    "physics",
    "physics",
    "physics",
    "physics",
    "chemistry",
    "physics",
    "physics",
    "physics",
    "chemistry",
    "chemistry",
    "physics",
    "physics",
    "chemistry",
    "chemistry",
    "physics",
    "chemistry",
];

module.exports = {
    own_questions,
    actual_labels,
};